[options]
admin_passwd = CAMBIA_ESTA_CLAVE_MAESTRA

db_host = localhost
db_port = 5432
db_user = odoo19
db_password = odoo19
db_template = template1



addons_path = C:\Desarrollo\Odoo 19\server\odoo\addons,C:\Desarrollo\Odoo 19\custom_addons,C:\Desarrollo\Odoo 19\OpenHRMS
data_dir = C:\Desarrollo\Odoo 19\data

http_interface = 127.0.0.1
http_port = 8070
gevent_port = 8073

workers = 0
max_cron_threads = 1

dbfilter = ^odoo19_.*$
list_db = True
log_level = info